#!/usr/bin/python3
#

import sys
import keyring
import requests
import json
from pywallet import wallet



#
# Create Wallet support functions
#

def create_hd():
    """From https://github.com/ranaroussi/pywallet"""
    # generate 12 word mnemonic seed
    seed = wallet.generate_mnemonic()

    # create bitcoin wallet
    w = wallet.create_wallet(network="BTC", seed=seed, children=1)
    return w


def create_bitgo_hd(base_url, headers, coin):
    url = base_url + "v2/" + coin + "/key"
    user_options = { "source": "bitgo"}
    r = requests.post(url, headers=headers, json=user_options)
    print_response(url, headers, r)
    return r.json()


def add_keychain(base_url, headers, coin, key):
    url = base_url + "v2/" + coin + "/key"
    headers["Content-Type"] = "application/json"
    user_options = { "pub": key["xpublic_key"]}
    r = requests.post(url, headers=headers, json=user_options)
    print_response(url, headers, r)
    return r.json()
    


#
# Functions to process commands
#
def print_help():
    print("btg command")
    print("command:")
    print("\tping                                  - Calls the ping api")
    print("\tsession                               - Returns session information")
    print("\tconstants                             - Returns client constants")
    print("\tme                                    - Returns current user profile")
    print("\tlist_keychains <COIN>                 - Lists keychains for a specific coin")
    print("\tlk <COIN>                             - Same as list_keychains")
    print("\tlist_wallets <COIN>                   - Lists wallets for a specific coin")
    print("\tlw <COIN>                             - Same as list_wallets")
    print("\tcreate_wallet_advanced <COIN> <LABEL> - Lists wallets for a specific coin")
    print("\tcwa <COIN> <LABEL>                    - Same as create_wallet_advanced")


def parse_args():
    if len(sys.argv) == 1:
        print_help()
        sys.exit()


def print_response(url, headers, r):
    print("url = '" + url + "'")
    print("status = " + str(r.status_code))
    print(json.dumps(dict(r.headers), indent=4, sort_keys=True))
    j = json.loads(r.text)
    print(json.dumps(j, indent=4, sort_keys=True))


def cmd_ping(base_url):
    url = base_url + "v2/ping"
    r = requests.get(url)
    print_response(url, None, r)


def cmd_constants(base_url, headers):
    url = base_url + "v1/client/constants"
    r = requests.get(url)
    print_response(url, headers, r)


def cmd_me(base_url, headers):
    url = base_url + "v2/user/me"
    r = requests.get(url, headers=headers)
    print_response(url, headers, r)


def cmd_session(base_url, headers):
    url = base_url + "v2/user/session"
    r = requests.get(url, headers=headers)
    print_response(url, headers, r)


def cmd_list_keychains(base_url, headers, coin):
    url = base_url + "v2/" + coin + "/key"
    r = requests.get(url, headers=headers)
    print_response(url, headers, r)


def cmd_list_wallets(base_url, headers, coin):
    url = base_url + "v2/" + coin + "/wallet"
    r = requests.get(url, headers=headers)
    print_response(url, headers, r)


def cmd_create_wallet_advanced(base_url, headers, coin, wallet_label):
    user_key = create_hd()
    print("user key = " + str(user_key));
    user_keychain = add_keychain(base_url, headers, coin, user_key)
    user_key_id = user_keychain["id"]

    # This is where you would securely store user key material
    # Just an example -- store what you need
    keyring.set_password(keyring_system, "user_xprivate_key", user_key["xprivate_key"])
    keyring.set_password(keyring_system, "user_key_id", user_key_id)

    backup_key = create_hd()
    print("backup key = " + str(backup_key))
    backup_keychain = add_keychain(base_url, headers, coin, backup_key)
    backup_key_id = backup_keychain["id"]

    # This is where you would securely store backup key material
    # Just an example -- store what you need
    keyring.set_password(keyring_system, "backup_xprivate_key", backup_key["xprivate_key"])
    keyring.set_password(keyring_system, "backup_key_id", backup_key_id)

    bitgo_keychain = create_bitgo_hd(base_url, headers, coin)
    bitgo_key_id = bitgo_keychain["id"]

    url = base_url + "v2/" + coin + "/wallet"

    user_options = { "label": wallet_label, "m": 2, "n": 3, "keys": [ user_key_id, backup_key_id, bitgo_key_id]}
    print("create bitgo key: data = '" + str(user_options) + "'")
    r = requests.post(url, headers=headers, json=user_options)
    print_response(url, headers, r)


#
# Constants / configs - move to external file
#

# Use BitGo Express if you don't want the key to fly over the wire
#base_url = "http://localhost:3080/api/"
base_url = "https://test.bitgo.com/api/"

# keyring directory
keyring_system = "bitgo"
keyring_api_key_key = "api_key"


#
# MAIN
#

parse_args()


command = sys.argv[1]
num_args = len(sys.argv)

if command != "ping":
    api_key = keyring.get_password(keyring_system, keyring_api_key_key)
    headers = {"Authorization": "Bearer " + api_key}
    #print("api key is '" + api_key + "'")


if command == "ping":
    cmd_ping(base_url)
elif command == "constants":
    cmd_constants(base_url, headers)
elif command == "me":
    cmd_me(base_url, headers)
elif command == "session":
    cmd_session(base_url, headers)
elif command == "list_keychains" or command == "lk":
    if num_args >= 3:
        cmd_list_keychains(base_url, headers, sys.argv[2])
    else:
        print("list_keychains needs a coin, such as tbtc")
elif command == "list_wallets" or command == "lw":
    if num_args >= 3:
        cmd_list_wallets(base_url, headers, sys.argv[2])
    else:
        print("list_wallets needs a coin, such as tbtc")
elif command == "create_wallet_advanced" or command == "cwa":
    if num_args >= 4:
        cmd_create_wallet_advanced(base_url, headers, sys.argv[2], sys.argv[3])
    else:
        print("create_wallet_advanced needs a coin and a wallet label")
else:
    print("Command '" + command + "' not recognized")



